---
# - name: 'iquippo-build-creation'
- hosts: "{{ HOST }}"
  become: true
  become_user: "{{ become_user }}"
  become_method: su
  gather_facts: true
  
  tasks:
    - stat:
        path: "{{ app_path }}/{{ app_dir }}"
      register: exist

    - name: create "{{ app_path }}/{{ app_dir }}" directory
      file: dest={{ app_path }}/{{ app_dir }} state=directory 
      when: exist.stat.exists != True

