---
- hosts: "{{ HOST }}"
  become: true
  become_user: "{{ become_user }}"
  become_method: su
  gather_facts: true
  
  tasks:
    - name: install mysql-server
      apt: name=mysql-server state=present update_cache=yes

    - name: install ansible dependencies
      apt: name=python-mysqldb state=present

    - name: Ensure mysql is running 
      service: name=mysql state=started


